name: Coverage
on:
  workflow_dispatch:
jobs:
  calculate-coverage:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "corretto"
          cache: "maven"
      - name: Generate coverage report
        run: mvn -B test -T 2C --file pom.xml -Dexclude=**/RaftBrokerHeartBeatManagerTest.java
        if: runner.os != 'Linux'
      - name: Generate coverage report
        run: mvn -B test -T 2C --file pom.xml
        if: runner.os == 'Linux'
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
          token: cf0cba0a-22f8-4580-89ab-4f1dec3bda6f
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
